# Generated by Django 4.0.3 on 2022-04-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('brand', '0001_initial'),
        ('review', '0002_productreview_remove_wearsreview_product_and_more'),
        ('product', '0002_product_productimagealbum_remove_gadget_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gadget',
        ),
        migrations.DeleteModel(
            name='Wears',
        ),
        migrations.AddField(
            model_name='productimagealbum',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='brand.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='category.category'),
        ),
    ]
