# Generated by Django 4.0.3 on 2022-04-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_rating_alter_product_rating_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
    ]
